version: '3.1'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'npm run dev'
    env_file:
      - .env
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - db
  
  db:
    image: postgres:12.5-alpine
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 5435:5432